apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    name: app-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: empapp
  type: LoadBalancer
