apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USERNAME: root
  MYSQL_PASSWORD: root
  
#No need for this file, because i am using mysql image from my dockerhub. i.e image name is kube_mysql
